# Оригинал данного прототипа был сделан @temporaldarkness (discord). Прототип был взят с https://github.com/ss14-ganimed/ENT14-Master.
# Ganimed-Book-Printer-Start
- type: entity
  id: CrateServicePrinterInkCartridge
  parent: CratePlastic
  components:
  - type: StorageFill
    contents:
      - id: BookPrinterInkCartridge
# Ganimed-Book-Printer-End